### ISSUE TITLE
Font styles

### ISSUE THREAD

**Issue by jrd656** [WebAhead5/ZooVisit#6]
This is nothing major, but I think it might be worth trying some other font styles.

Try adding the following to HTML
`<link` href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">`

And the following to CSS:
`font-family: 'Work Sans', sans-serif;`

https://learnui.design/blog/7-rules-for-creating-gorgeous-ui-part-2.html#rule-6-use-only-good-fonts

This page is super helpful for font advice

**Comment by amirfahoum** [comment]
great advice James ,we will take a look on that page
