### ISSUE TITLE
CSS !important

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/ZooVisit#7]
`!important` is considered a bad practice in CSS cause if you have bigger plans fr your website then it's going to make it really hard to style it further ([talking about this code here](https://github.com/WebAhead5/ZooVisit/blob/master/style/style.css#L105-L123))

[further explanations](https://stackoverflow.com/a/3706876/9096274)

**Comment by amirfahoum** [comment]
you're totally right, now we will change it
